name: My Firts Workflow de GitHub Actions

on:
  push:
    branches: 
      - main 
  pull_request:
    branches: 
      - main
  workflow-dispatch:
jobs:
  imprimir_info:  
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3 

      - name: Santiago Hoyos Dorado
        run: |
          echo "Hola, mi nombre es Santiago Hoyos Dorado y este es mi primer workflow!"  
          echo "La fecha y hora actual es: $(date)"  
        
      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Ejecutar script Python
        run: python mi_script.py 